[phases.setup]
nixPkgs = ["python313", "pip"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build] 
cmds = ["echo 'Build completed successfully'"]

[start]
cmd = "uvicorn src.api.main:app --host 0.0.0.0 --port $PORT"
